### ISSUE TITLE
Yarn parsing is panicing

### ISSUE THREAD

**Issue by milesj** [robertohuertasm/yarn-lock-parser#10]
@robertohuertasm Thanks for this lib, I've been using it in moon: https://moonrepo.dev

With that being said, I've actually hit an instance where yarn parsing panics, which can be seen here: https://github.com/milesj/packemon/actions/runs/3536269434/jobs/5935523513

I've briefly looked into it, but can't tell what version entry is causing the panic, and that error output is rough to read. Here's the PR that caused it: https://github.com/milesj/packemon/pull/168

**Comment by robertohuertasm** [comment]
Hi @milesj, I'll take a look at it when I have some time. Thanks for letting me know! 🙌🏻

**Comment by robertohuertasm** [comment]
Is this [yarn.lock file](https://github.com/milesj/packemon/blob/moon/yarn.lock) the offender? I can't seem to reproduce the error.

**Comment by milesj** [comment]
@robertohuertasm Yeah it is.

It doesn't fail for me locally either, but fails in CI, so it's been rather annoying to try and figure out the root cause. Let me dig some more.

**Comment by milesj** [comment]
It looks to only be happening on Windows.

**Comment by robertohuertasm** [comment]
Ok, I tested this yesterday in WSL. I will test it directly in Windows then and see if I can reproduce it. Thanks for the hint!

**Comment by robertohuertasm** [comment]
It works for me on Windows... Still unable to reproduce it 😞

**Comment by robertohuertasm** [comment]
I've created a PR to run the test on Windows in the CI and got the error. It's failing on Windows Server 2022. Testing it right now on Windows Server 2019. Locally, it works for me on Windows 11, but with this I think I can work to find the issue.

**Comment by robertohuertasm** [comment]
I'm still not sure what's going on but it's only affecting tests reading from a file. All the tests that work with memory are passing.

**Comment by robertohuertasm** [comment]
Ok, I got the error. It was related to the `endline` char. Windows Server still uses `\r\n` instead of just `\n` and there was a bug in the current code. I'm working on a fix. I'll let you know once it's fixed.

**Comment by robertohuertasm** [comment]
@milesj `v0.4.1` is on its way to crates.io!

**Comment by milesj** [comment]
@robertohuertasm Awesome 🙏  Thanks for the quick response and fix, much appreciated!
