### ISSUE TITLE
Panic when parsing some files

### ISSUE THREAD

**Issue by kmod-midori** [robertohuertasm/yarn-lock-parser#13]
[upload_file_iwl.iDashboard.git.zip](https://github.com/robertohuertasm/yarn-lock-parser/files/11198646/upload_file_iwl.iDashboard.git.zip)
[upload_file_leo108.php_cas_server.git.zip](https://github.com/robertohuertasm/yarn-lock-parser/files/11198648/upload_file_leo108.php_cas_server.git.zip)

```
thread 'main' panicked at 'Error parsing Entry: Error(VerboseError { errors: [("", Nom(TakeUntil)), ("", Nom(Alt)), ("", Context("descriptors")), ("", Context("entry"))] })', /home/chengyuhui/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/yarn-lock-parser-0.4.1/src/lib.rs:99:50
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::expect
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1069:23
   4: yarn_lock_parser::entry_final::{{closure}}
             at /home/chengyuhui/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/yarn-lock-parser-0.4.1/src/lib.rs:99:29
   5: core::result::Result<T,E>::map
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:774:25
   6: yarn_lock_parser::entry_final
             at /home/build/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/yarn-lock-parser-0.4.1/src/lib.rs:98:5
   7: yarn_lock_parser::parse
             at /home/build/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/yarn-lock-parser-0.4.1/src/lib.rs:62:28
   8: yarn_lock_parser::parse_str
             at /home/build/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/yarn-lock-parser-0.4.1/src/lib.rs:45:5
```

I have attached the full projects, in case someone needs them (but this library should not panic anyway).

**Comment by robertohuertasm** [comment]
Thanks for reporting this

**Comment by robertohuertasm** [comment]
@chengyuhui it seems that your `yarn.lock` file has an extra empty string in the end. Did you add it manually? Or maybe one of the tools you're using?

**Comment by kmod-midori** [comment]
These projects are directly cloned from public online repositories, and I doubt the maintainers will manually touch `yarn.lock` files.

**Comment by kmod-midori** [comment]
It is actually possible to crash the parser with inputs as simple as
```
\

@
```
(Base64: XAoKQA==)
and
```


*
```
(Base64: Cgoq)

I found these with `cargo-fuzz`. Maybe we should not panic in `entry_final`?

The places I found to be problematic (easily crashable) are:
* `expect` on L99
* `expect` on L110
* `assert_ne` on L171

However, I do think that the lock files provided in the original issue are valid, and we need to accept them.

**Comment by robertohuertasm** [comment]
The idea is that the library will crash if the input is not a valid `yarn.lock` file. 

I couldn't replicate these empty lines in the end of the file when generating a v1 `yarn.lock` file so that's why I was wondering if in those repos they were using a particular tool or something that could have modified them.

Regarding your last message, I didn't have the time to check it out. But in any case, if those characters could be found in a valid `yarn.lock` file, then we should support them. If not, I'm not sure if we should consider them.

**Comment by kmod-midori** [comment]
I don't think crashing is a good idea, as it can be difficult or even impossible to recover from a `panic` depending on compiling settings and the target environment.

We've found more than 5 instances of this library crashing on (seemingly) valid lock files found in the wild, so I'm pretty sure that there are tools that generate files with extra empty lines.

**Comment by robertohuertasm** [comment]
You have a point. To be honest I built it for a particular use case. Would you mind sharing what are you using this library for? I'm curious about your use case.

**Comment by kmod-midori** [comment]
We are developing a tool similar to GitHub's dependabot, where `yarn.lock` files, along with other locking files and specs (such as `pom.xml`) are processed for a dependency tree, which is then scanned for known vulnerabilitles and upgrades.

The problem here is that it is quite possible to encounter invalid files (or files that have been manually modified) in our use case. For example, suppose we are scanning a project similar to this project (a `yarn.lock` parser), it may have tese cases that intentinally contain invalid lock files, and we really don't want these files to crash the whole application.

**Comment by robertohuertasm** [comment]
Thanks for sharing @chengyuhui. I'm developing something similar myself so I can see your motivation and I think you have a valid point.

I'll work on that when I have some time and try to fix that behavior.
