### ISSUE TITLE
Get `checksum` and other fields

### ISSUE THREAD

**Issue by IgnisDa** [robertohuertasm/yarn-lock-parser#8]
Awesome library!

I don't see any way to get a package's `checksum` (or `integrity` in yarn classic). Is there something I am missing?

**Comment by robertohuertasm** [comment]
Hi @IgnisDa we're not exposing that. I guess you need it... let me see what we can do.

**Comment by IgnisDa** [comment]
Alright, will be awesome if you look into this!

**Comment by robertohuertasm** [comment]
@IgnisDa I've exposed a new `integrity` property. It will contain either the `integrity` value in `v1` or the `checksum` value in `v2`.

Regarding the rest of fields, they're only available in `v2`. Would you need them, too?

**Comment by IgnisDa** [comment]
@robertohuertasm Thank you so much for the swift implementation! I do not need the other fields for now, but it would be good to make the library future-proof, right?

**Comment by IgnisDa** [comment]
Either way, it is not that important so support for other fields can be implemented later (or in a separate issue altogether).

**Comment by robertohuertasm** [comment]
I've just published version 0.4.0 with integrity support. The implementation for the rest of fields to be exposed will have to wait as I don't have enough time right now. Probably the easiest way to do that would be to just exposes a collection of  `(prop_name: value)`  tuples.
